### ISSUE TITLE
Collector Config in Agent Configuration

### ISSUE THREAD

**Issue by Choidaeboem** [snetsystems/cmp#123]
Report a two problem
1. If you edit and apply the telegraf configuration, and then reload it, there is a new line at the bottom.
2. When editing the configuration, the first input is sometimes ignored.

**Comment by Choidaeboem** [comment]
2. When editing the configuration, the first input is sometimes ignored.

this is not fixed

**Comment by snetsystems** [comment]
The above 2 has not happened by now.
If it will happen later, reopen this issue.
