### ISSUE TITLE
DMT firmware version and configuration update via Salt-Stack

### ISSUE THREAD

**Issue by snetsystems** [snetsystems/cmp#82]
1. Find the way to run two salt-minion processes of each other version
2. Detect if the file update. #92 #93 
3. Deploy file to the specified path via Salt-Stack.

**Comment by minsoo77** [comment]
- [Test bed](https://seversky.atlassian.net/wiki/spaces/CM/pages/145817601/Salt-minion?atlOrigin=eyJpIjoiZTM1MWE3MDljMjdiNDMyMWIzNDNjYmZmYzM0MWE1ZjciLCJwIjoiYyJ9)

**Comment by minsoo77** [comment]
3. salt file server path for DMT

Firmware - /srv/salt/prod/dmt/firmware
Config - /srv/salt/prod/dmt/config
